package timeelapsed;

import java.awt.*;
import java.awt.Color;
import java.awt.FileDialog;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class JFrameForm extends javax.swing.JFrame{

	// Strings for pathnames selected by user and displayed in JLabels.
	String path1;
	String path2;
	String path3;
	
	// For adding more files if using the program more than once before closing.
	// i will be incremented after each use and will be appended to 'elapsed_times.txt'.
	// Ex. First generation: 'elapsed_times1.txt'. Second generation: 'elapsed_times2.txt'.
	int i;
	
	// Creates new form JFrameForm.
	public JFrameForm(){
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form. 
	 * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        operation_successful = new javax.swing.JLabel();
        resulting_path = new javax.swing.JLabel();
        delivery_times_button = new javax.swing.JButton();
        done_button = new javax.swing.JButton();
        save_location_button = new javax.swing.JButton();
        order_times_button = new javax.swing.JButton();
        app_title = new javax.swing.JLabel();
        save_location = new javax.swing.JLabel();
        delivery_times_path = new javax.swing.JLabel();
        order_times_path = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Elapsed");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(10, 10, 10));

        operation_successful.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        operation_successful.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operation_successful.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-mark.png"))); // NOI18N
        operation_successful.setText("   Operation successful. File saved to:");
        operation_successful.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        resulting_path.setFont(new java.awt.Font("Courier", 1, 14)); // NOI18N
        resulting_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resulting_path.setText("jLabel1");

        delivery_times_button.setBackground(new java.awt.Color(10, 10, 10));
        delivery_times_button.setFont(new java.awt.Font("Gill Sans", 0, 15)); // NOI18N
        delivery_times_button.setForeground(new java.awt.Color(223, 223, 250));
        delivery_times_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delivery-times-button.png"))); // NOI18N
        delivery_times_button.setBorder(null);
        delivery_times_button.setFocusPainted(false);
        delivery_times_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delivery_times_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delivery_times_buttonActionPerformed(evt);
            }
        });

        done_button.setBackground(new java.awt.Color(10, 10, 10));
        done_button.setFont(new java.awt.Font("Gill Sans", 0, 16)); // NOI18N
        done_button.setForeground(new java.awt.Color(223, 223, 250));
        done_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/done-button.png"))); // NOI18N
        done_button.setBorder(null);
        done_button.setFocusPainted(false);
        done_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_buttonActionPerformed(evt);
            }
        });

        save_location_button.setBackground(new java.awt.Color(10, 10, 10));
        save_location_button.setFont(new java.awt.Font("Gill Sans", 0, 15)); // NOI18N
        save_location_button.setForeground(new java.awt.Color(223, 223, 250));
        save_location_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-location-button.png"))); // NOI18N
        save_location_button.setBorder(null);
        save_location_button.setFocusPainted(false);
        save_location_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_location_button.setMargin(new java.awt.Insets(2, 15, 2, 15));
        save_location_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_location_buttonActionPerformed(evt);
            }
        });

        order_times_button.setBackground(new java.awt.Color(10, 10, 10));
        order_times_button.setFont(new java.awt.Font("Gill Sans", 0, 15)); // NOI18N
        order_times_button.setForeground(new java.awt.Color(223, 223, 250));
        order_times_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/order-times-button.png"))); // NOI18N
        order_times_button.setBorder(null);
        order_times_button.setBorderPainted(false);
        order_times_button.setFocusPainted(false);
        order_times_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        order_times_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_times_buttonActionPerformed(evt);
            }
        });

        app_title.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        app_title.setForeground(new java.awt.Color(204, 204, 255));
        app_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app_title.setText("Time Elapsed");
        app_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        save_location.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        save_location.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_location.setText("jLabel1");

        delivery_times_path.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        delivery_times_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delivery_times_path.setText("jLabel1");

        order_times_path.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        order_times_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_times_path.setText("jLabel1");
        order_times_path.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delivery_times_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(order_times_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resulting_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operation_successful, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(delivery_times_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(267, 267, 267))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(save_location_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(272, 272, 272))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(done_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(393, 393, 393))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(order_times_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(278, 278, 278))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(app_title, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(app_title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(order_times_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(order_times_path)
                .addGap(30, 30, 30)
                .addComponent(delivery_times_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(delivery_times_path)
                .addGap(26, 26, 26)
                .addComponent(save_location_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(save_location)
                .addGap(28, 28, 28)
                .addComponent(done_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(operation_successful)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resulting_path)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        operation_successful.setVisible(false);
        resulting_path.setVisible(false);
        save_location.setVisible(false);
        delivery_times_path.setVisible(false);
        order_times_path.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void order_times_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_times_buttonActionPerformed
		// Display File Explorer or Finder for file selection.
		FileDialog file_dialog_order_times = new FileDialog(this, "Choose a file", FileDialog.LOAD);
        file_dialog_order_times.setVisible(true);
			
		// Save the absolute path of chosen file.
		path1 = file_dialog_order_times.getDirectory() + file_dialog_order_times.getFile();
        if(path1.startsWith("null")) path1 = "";
                
		// Display path to chosen file.
		order_times_path.setText(path1);
		order_times_path.setForeground(new Color(255, 255, 255));
		order_times_path.setVisible(true);
    }//GEN-LAST:event_order_times_buttonActionPerformed

    private void done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_buttonActionPerformed
        // New TimeElapsed object to run calculations.
		TimeElapsed time_elapsed = new TimeElapsed();
		
		int returnVal = 0;
		// Boolean becomes true upon successful execution of timeElapsed().
		try {
			returnVal = time_elapsed.timeElapsed(path1, path2, path3, i);
		} catch (IOException ex) {
			Logger.getLogger(JFrameForm.class.getName()).log(Level.SEVERE, null, ex);
		}
			
		// Display confirmation of file creation along with path to the newly created file.
		if(returnVal >= 0){
			i = returnVal;
			// Display operation successful confirmation.
			operation_successful.setForeground(new Color(246, 246, 246));
			operation_successful.setVisible(true);
			
			// Display resulting path to the newly created file.
			System.out.println(i);
			resulting_path.setText(path3 + "elapsed_times" + i + ".txt");
			resulting_path.setForeground(new Color(246, 255, 166));
			resulting_path.setVisible(true);
		}
    }//GEN-LAST:event_done_buttonActionPerformed

    private void delivery_times_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delivery_times_buttonActionPerformed
        // Display File Explorer or Finder for file selection.
		FileDialog file_dialog_delivery_times = new FileDialog(this, "Choose a file", FileDialog.LOAD);
		file_dialog_delivery_times.setVisible(true);
			
		// Save the absolute path of chosen file.
		path2 = file_dialog_delivery_times.getDirectory() + file_dialog_delivery_times.getFile();
        if(path2.startsWith("null")) path2 = "";
                
		// Display path to chosen file.
		delivery_times_path.setText(path2);
		delivery_times_path.setForeground(new Color(255, 255, 255));
		delivery_times_path.setVisible(true);
    }//GEN-LAST:event_delivery_times_buttonActionPerformed

    private void save_location_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_location_buttonActionPerformed
        // Display File Explorer or Finder for file selection.
		JFileChooser directory_save_path = new JFileChooser();
		directory_save_path.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		
		int response = directory_save_path.showOpenDialog(this);
		
		if(response == JFileChooser.APPROVE_OPTION){
			// Save the absolute path of chosen file.
			if(System.getProperty("os.name").startsWith("Windows")) 
                            path3 = directory_save_path.getSelectedFile().getAbsolutePath() + "\\";
			
            else path3 = directory_save_path.getSelectedFile().getAbsolutePath() + "/";
			
            if(path3.startsWith("null")) path3 = "";
                        
			// Display path to chosen file.
			save_location.setText(path3);
			save_location.setForeground(new Color(255, 255, 255));
			save_location.setVisible(true);
		}
    }//GEN-LAST:event_save_location_buttonActionPerformed

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFrameForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_title;
    private javax.swing.JButton delivery_times_button;
    private javax.swing.JLabel delivery_times_path;
    private javax.swing.JButton done_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel operation_successful;
    private javax.swing.JButton order_times_button;
    private javax.swing.JLabel order_times_path;
    private javax.swing.JLabel resulting_path;
    private javax.swing.JLabel save_location;
    private javax.swing.JButton save_location_button;
    // End of variables declaration//GEN-END:variables
}
